name: Lanfeng Pan's Website
description: Thoughts about statistics
permalink: /:categories/:year/:month/:title/
url: http://panlanfeng.github.io
markdown: kramdown
highlighter: rouge

navigation:
  - url: "/blog/"
    title: Blog
  - url: "/Chinese/"
    title: 博客
  - title: Github
    url: "http://github.com/panlanfeng"
