permalink: /:categories/:year/:month/:title

highlighter: rouge
site: http://panlanfeng.github.io
    
navigation:
  - url: "/about/"
    title: CV
  - url: "/blog/"
    title: Blog
  - url: "/Chinese/"
    title: 博客
  - title: Github
    url: "https://github.com/panlanfeng" 
