permalink: /:categories/:year/:month/:title

highlighter: rough
    
navigation:
  - url: "/about/"
    title: CV
  - url: "/blog/"
    title: Blog
  - url: "/Chinese/"
    title: 中文
  - title: Github
    url: "https://github.com/panlanfeng" 
